/* ─── Shared Roadmap Data — Single Source of Truth ──────────────────── */
import type { RoadmapProgress } from "@/types";

export interface RoadmapTopic {
  id: string;
  label: string;
}

export interface RoadmapPhase {
  id: number;
  title: string;
  subtitle: string;
  duration: string;
  dateStart: string;
  dateEnd: string;
  icon: string;
  color: string;
  bgColor: string;
  gradient: string;
  borderColor: string;
  goal: string;
  topics: RoadmapTopic[];
  practice: string;
  milestones: string[];
  platforms?: string[];
}

export const ROADMAP_PHASES: RoadmapPhase[] = [
  {
    id: 1,
    title: "Python Programming Mastery",
    subtitle: "Mar 14 – Apr 27",
    duration: "Mar 14 – Apr 27 (6 weeks)",
    dateStart: "2026-03-14",
    dateEnd: "2026-04-27",
    icon: "01",
    color: "text-emerald-400",
    bgColor: "bg-emerald-500",
    gradient: "from-emerald-500/20 to-emerald-500/0",
    borderColor: "border-emerald-500/20",
    goal: "Master Python as your primary interview language.",
    topics: [
      { id: "p1-variables", label: "Variables & Data Types (int, float, str, bool)" },
      { id: "p1-type-casting", label: "Type Casting & Type Checking" },
      { id: "p1-operators", label: "Operators (arithmetic, comparison, logical, bitwise)" },
      { id: "p1-string-formatting", label: "String Formatting (f-strings, .format)" },
      { id: "p1-input-output", label: "Input / Output & File I/O" },
      { id: "p1-conditionals", label: "Conditionals (if / elif / else)" },
      { id: "p1-for-loops", label: "For Loops & Range" },
      { id: "p1-while-loops", label: "While Loops & Break / Continue / Pass" },
      { id: "p1-comprehensions", label: "List / Dict / Set Comprehensions" },
      { id: "p1-lists", label: "Lists (slicing, methods, copying)" },
      { id: "p1-tuples", label: "Tuples & Named Tuples" },
      { id: "p1-sets", label: "Sets & Frozen Sets" },
      { id: "p1-dicts", label: "Dictionaries (methods, defaultdict, Counter)" },
      { id: "p1-strings", label: "String Methods & Manipulation" },
      { id: "p1-functions", label: "Functions (params, return, default args)" },
      { id: "p1-args-kwargs", label: "*args, **kwargs & Unpacking" },
      { id: "p1-lambda", label: "Lambda Functions & map / filter / reduce" },
      { id: "p1-closures", label: "Closures & Decorators" },
      { id: "p1-generators", label: "Generators & Iterators (yield)" },
      { id: "p1-classes", label: "Classes & Objects" },
      { id: "p1-inheritance", label: "Inheritance & Polymorphism" },
      { id: "p1-encapsulation", label: "Encapsulation & Abstraction" },
      { id: "p1-dunder", label: "Dunder Methods (__init__, __str__, __repr__, __eq__)" },
      { id: "p1-dataclasses", label: "Dataclasses & @property" },
      { id: "p1-exceptions", label: "Exception Handling (try/except/finally/raise)" },
      { id: "p1-collections", label: "Collections Module (deque, OrderedDict, ChainMap)" },
      { id: "p1-itertools", label: "itertools (permutations, combinations, product)" },
      { id: "p1-functools", label: "functools (lru_cache, partial, reduce)" },
      { id: "p1-regex", label: "Regular Expressions (re module)" },
      { id: "p1-sorting", label: "Custom Sorting (key, cmp_to_key, lambda)" },
      { id: "p1-bisect", label: "bisect Module (binary search helpers)" },
      { id: "p1-heapq", label: "heapq Module (min-heap operations)" },
    ],
    practice: "Solve 3–5 easy LeetCode problems daily in Python. Focus on clean syntax.",
    milestones: [
      "Comfortable writing Python without docs",
      "50+ easy problems solved",
      "Can implement basic data structures from scratch",
    ],
    platforms: ["LeetCode", "HackerRank", "Python.org Docs"],
  },
  {
    id: 2,
    title: "Data Structures Deep Dive",
    subtitle: "Apr 28 – Jun 15",
    duration: "Apr 28 – Jun 15 (7 weeks)",
    dateStart: "2026-04-28",
    dateEnd: "2026-06-15",
    icon: "02",
    color: "text-blue-400",
    bgColor: "bg-blue-500",
    gradient: "from-blue-500/20 to-blue-500/0",
    borderColor: "border-blue-500/20",
    goal: "Implement and deeply understand every core data structure.",
    topics: [
      { id: "p2-arrays-basics", label: "Arrays: Static vs Dynamic, Memory Layout" },
      { id: "p2-arrays-ops", label: "Arrays: Insert, Delete, Search, Rotate" },
      { id: "p2-arrays-2d", label: "2D Arrays / Matrices & Traversal Patterns" },
      { id: "p2-prefix-sum", label: "Prefix Sums & Difference Arrays" },
      { id: "p2-string-ops", label: "Strings: Immutability, StringBuilder Pattern" },
      { id: "p2-string-encoding", label: "String Encoding (ASCII, Unicode, UTF-8)" },
      { id: "p2-anagram", label: "Anagram, Palindrome & Substring Problems" },
      { id: "p2-singly-ll", label: "Singly Linked List (insert, delete, reverse)" },
      { id: "p2-doubly-ll", label: "Doubly Linked List & Circular Linked List" },
      { id: "p2-ll-patterns", label: "LL Patterns: Fast/Slow Pointer, Merge, Cycle Detection" },
      { id: "p2-lru-cache", label: "LRU Cache (HashMap + Doubly Linked List)" },
      { id: "p2-stack-basics", label: "Stack: Implementation & Operations" },
      { id: "p2-monotonic-stack", label: "Monotonic Stack (Next Greater Element)" },
      { id: "p2-stack-apps", label: "Stack Applications: Parentheses, Calculator, Decode" },
      { id: "p2-queue-basics", label: "Queue: Implementation, Circular Queue" },
      { id: "p2-deque", label: "Deque (Double-Ended Queue)" },
      { id: "p2-monotonic-queue", label: "Monotonic Deque (Sliding Window Maximum)" },
      { id: "p2-hash-basics", label: "Hash Tables: Hash Functions, Collision Handling" },
      { id: "p2-hash-chaining", label: "Open Addressing vs Separate Chaining" },
      { id: "p2-hash-apps", label: "Hash Map Applications: Two Sum, Group Anagrams" },
      { id: "p2-hash-design", label: "Design HashMap from Scratch" },
      { id: "p2-binary-tree", label: "Binary Tree: Traversals (Inorder, Pre, Post, Level)" },
      { id: "p2-bst", label: "Binary Search Tree: Insert, Delete, Search, Validate" },
      { id: "p2-balanced-trees", label: "Balanced Trees: AVL, Red-Black Tree (concepts)" },
      { id: "p2-tree-patterns", label: "Tree Patterns: LCA, Diameter, Path Sum, Serialize" },
      { id: "p2-nary-tree", label: "N-ary Trees & Tree Reconstruction" },
      { id: "p2-heap-basics", label: "Heap: Min-Heap, Max-Heap, Heapify" },
      { id: "p2-heap-sort", label: "Heap Sort & Priority Queue" },
      { id: "p2-heap-apps", label: "Heap Apps: Top K, Median Finder, Merge K Sorted" },
      { id: "p2-trie-basics", label: "Trie: Insert, Search, StartsWith" },
      { id: "p2-trie-apps", label: "Trie Apps: Autocomplete, Word Search, Word Break" },
      { id: "p2-graph-basics", label: "Graph: Adjacency List vs Matrix, Directed/Undirected" },
      { id: "p2-graph-weighted", label: "Weighted Graphs & Edge Lists" },
      { id: "p2-graph-representations", label: "Graph: In-degree, Out-degree, Connected Components" },
      { id: "p2-union-find", label: "Disjoint Set / Union-Find (Path Compression, Union by Rank)" },
      { id: "p2-segment-tree", label: "Segment Tree (Range Queries & Updates)" },
      { id: "p2-bit", label: "Binary Indexed Tree / Fenwick Tree" },
    ],
    practice: "5+ medium problems daily. Implement each structure from scratch at least once.",
    milestones: [
      "150+ total problems (50 medium+)",
      "Can explain time complexity of all operations",
      "Implement any structure in <20 minutes",
    ],
    platforms: ["LeetCode", "NeetCode.io", "Visualgo.net"],
  },
  {
    id: 3,
    title: "Core Algorithms & Patterns",
    subtitle: "Jun 16 – Jul 27",
    duration: "Jun 16 – Jul 27 (6 weeks)",
    dateStart: "2026-06-16",
    dateEnd: "2026-07-27",
    icon: "03",
    color: "text-violet-400",
    bgColor: "bg-violet-500",
    gradient: "from-violet-500/20 to-violet-500/0",
    borderColor: "border-violet-500/20",
    goal: "Master algorithm design patterns used in 80% of interview problems.",
    topics: [
      { id: "p3-sort-basic", label: "Sorting: Bubble, Selection, Insertion" },
      { id: "p3-sort-efficient", label: "Sorting: Merge Sort & Quick Sort (in-depth)" },
      { id: "p3-sort-noncomp", label: "Non-Comparison Sorts: Counting, Radix, Bucket" },
      { id: "p3-sort-custom", label: "Custom Sorting: Comparators, Stability, Timsort" },
      { id: "p3-binary-search", label: "Binary Search: Standard, Lower/Upper Bound" },
      { id: "p3-bs-variants", label: "Binary Search on Answer, Rotated Array, Matrix" },
      { id: "p3-bs-advanced", label: "Binary Search: Kth Element, Peak Finding" },
      { id: "p3-two-ptr-opposite", label: "Two Pointers: Opposite Direction (3Sum, Container)" },
      { id: "p3-two-ptr-same", label: "Two Pointers: Same Direction (Remove Duplicates)" },
      { id: "p3-two-ptr-partition", label: "Two Pointers: Partition, Dutch National Flag" },
      { id: "p3-sw-fixed", label: "Sliding Window: Fixed Size (Max Sum Subarray)" },
      { id: "p3-sw-variable", label: "Sliding Window: Variable Size (Min Window Substring)" },
      { id: "p3-sw-hash", label: "Sliding Window + Hash Map Patterns" },
      { id: "p3-recursion", label: "Recursion: Base Case, Recursive Tree, Call Stack" },
      { id: "p3-backtrack-subsets", label: "Backtracking: Subsets, Permutations, Combinations" },
      { id: "p3-backtrack-constraints", label: "Backtracking: N-Queens, Sudoku, Word Search" },
      { id: "p3-backtrack-pruning", label: "Pruning & Optimization Techniques" },
      { id: "p3-greedy-intervals", label: "Greedy: Interval Scheduling, Merge Intervals" },
      { id: "p3-greedy-general", label: "Greedy: Jump Game, Gas Station, Task Scheduler" },
      { id: "p3-greedy-proof", label: "Greedy: When to Use & Proof of Correctness" },
      { id: "p3-dnc-merge", label: "Divide & Conquer: Merge Sort, Quick Select" },
      { id: "p3-dnc-closest", label: "Divide & Conquer: Closest Pair, Count Inversions" },
      { id: "p3-bit-basics", label: "Bit Manipulation: AND, OR, XOR, NOT, Shifts" },
      { id: "p3-bit-tricks", label: "Bit Tricks: Power of 2, Count Bits, Single Number" },
      { id: "p3-bit-masks", label: "Bitmask: Subset Generation, States" },
      { id: "p3-math-gcd", label: "Math: GCD, LCM, Euclidean Algorithm" },
      { id: "p3-math-primes", label: "Math: Sieve of Eratosthenes, Prime Factorization" },
      { id: "p3-math-modular", label: "Modular Arithmetic & Fast Exponentiation" },
      { id: "p3-math-combinatorics", label: "Combinatorics (nCr, Pascal's Triangle)" },
    ],
    practice: "5 medium + 1 hard problem daily. Time yourself: 20min/medium, 40min/hard.",
    milestones: [
      "250+ total problems",
      "Recognize patterns within 2 minutes",
      "Solve most mediums in <25 minutes",
    ],
    platforms: ["LeetCode", "NeetCode Roadmap", "Codeforces (Div 2A-B)"],
  },
  {
    id: 4,
    title: "Dynamic Programming Mastery",
    subtitle: "Jul 28 – Aug 24",
    duration: "Jul 28 – Aug 24 (4 weeks)",
    dateStart: "2026-07-28",
    dateEnd: "2026-08-24",
    icon: "04",
    color: "text-fuchsia-400",
    bgColor: "bg-fuchsia-500",
    gradient: "from-fuchsia-500/20 to-fuchsia-500/0",
    borderColor: "border-fuchsia-500/20",
    goal: "Conquer DP — the most common hard-problem category at Google.",
    topics: [
      { id: "p4-dp-intro", label: "DP Foundations: Memoization vs Tabulation" },
      { id: "p4-dp-identify", label: "Identifying DP Problems: Overlapping Subproblems" },
      { id: "p4-dp-state", label: "State Definition & Transition Formulation" },
      { id: "p4-dp-fibonacci", label: "1D DP: Fibonacci, Climbing Stairs, House Robber" },
      { id: "p4-dp-jump", label: "1D DP: Jump Game, Decode Ways, Word Break" },
      { id: "p4-dp-lis", label: "Longest Increasing Subsequence (LIS)" },
      { id: "p4-dp-grid", label: "2D DP: Unique Paths, Grid Min Path, Matrix Chain" },
      { id: "p4-dp-lcs", label: "Longest Common Subsequence / Substring (LCS)" },
      { id: "p4-dp-edit", label: "Edit Distance (Levenshtein Distance)" },
      { id: "p4-dp-01-knapsack", label: "0/1 Knapsack: Subset Sum, Partition Equal Subset" },
      { id: "p4-dp-unbounded", label: "Unbounded Knapsack: Coin Change, Rod Cutting" },
      { id: "p4-dp-bounded", label: "Bounded Knapsack & Variations" },
      { id: "p4-dp-interval", label: "Interval DP: Burst Balloons, Matrix Chain Multiply" },
      { id: "p4-dp-palindrome", label: "Palindrome DP: Longest Palindromic Subsequence" },
      { id: "p4-dp-stock", label: "State Machine DP: Buy & Sell Stock (all variants)" },
      { id: "p4-dp-state-machine", label: "State Machine DP: Paint House, Paint Fence" },
      { id: "p4-dp-bitmask", label: "Bitmask DP: TSP, Assign Tasks, Matching" },
      { id: "p4-dp-tree", label: "DP on Trees: House Robber III, Binary Tree Cameras" },
      { id: "p4-dp-digit", label: "Digit DP: Count Numbers with Specific Properties" },
      { id: "p4-dp-string", label: "String DP: Regular Expression, Wildcard Matching" },
      { id: "p4-dp-optimization", label: "Space Optimization: Rolling Array Technique" },
    ],
    practice: "3 DP problems daily (mix medium+hard). Always write recurrence before coding.",
    milestones: [
      "320+ total problems",
      "Solve DP mediums in <20 minutes",
      "Can derive recurrence relations confidently",
    ],
    platforms: ["LeetCode DP Study Plan", "AtCoder DP Contest", "CSES Problem Set"],
  },
  {
    id: 5,
    title: "Graph Algorithms",
    subtitle: "Aug 25 – Sep 14",
    duration: "Aug 25 – Sep 14 (3 weeks)",
    dateStart: "2026-08-25",
    dateEnd: "2026-09-14",
    icon: "05",
    color: "text-orange-400",
    bgColor: "bg-orange-500",
    gradient: "from-orange-500/20 to-orange-500/0",
    borderColor: "border-orange-500/20",
    goal: "Master graph algorithms — a Google interview staple.",
    topics: [
      { id: "p5-bfs", label: "BFS: Level Order, Shortest Path (Unweighted)" },
      { id: "p5-dfs", label: "DFS: Connected Components, Cycle Detection" },
      { id: "p5-multi-source-bfs", label: "Multi-Source BFS (Rotting Oranges, 01 Matrix)" },
      { id: "p5-bidirectional-bfs", label: "Bidirectional BFS (Word Ladder)" },
      { id: "p5-dijkstra", label: "Dijkstra's Algorithm (Weighted Shortest Path)" },
      { id: "p5-bellman-ford", label: "Bellman-Ford (Negative Weights)" },
      { id: "p5-floyd-warshall", label: "Floyd-Warshall (All-Pairs Shortest Path)" },
      { id: "p5-astar", label: "A* Search (Heuristic Shortest Path)" },
      { id: "p5-topo-kahn", label: "Topological Sort: Kahn's Algorithm (BFS)" },
      { id: "p5-topo-dfs", label: "Topological Sort: DFS-based" },
      { id: "p5-topo-apps", label: "Applications: Course Schedule, Build Order, Alien Dict" },
      { id: "p5-kruskal", label: "Minimum Spanning Tree: Kruskal's Algorithm" },
      { id: "p5-prim", label: "Minimum Spanning Tree: Prim's Algorithm" },
      { id: "p5-tarjan", label: "Tarjan's SCC (Strongly Connected Components)" },
      { id: "p5-articulation", label: "Articulation Points & Bridges" },
      { id: "p5-bipartite", label: "Bipartite Check (Graph Coloring)" },
      { id: "p5-union-find-apps", label: "Union-Find Applications: Accounts Merge, Redundant" },
      { id: "p5-euler", label: "Euler Path / Circuit (Reconstruct Itinerary)" },
      { id: "p5-network-flow", label: "Network Flow Basics (Max Flow / Min Cut)" },
      { id: "p5-kmp", label: "KMP Algorithm (Pattern Matching)" },
      { id: "p5-rabin-karp", label: "Rabin-Karp (Rolling Hash)" },
      { id: "p5-manacher", label: "Manacher's Algorithm (Longest Palindromic Substring)" },
    ],
    practice: "3–4 graph + string problems daily. Draw out examples before coding.",
    milestones: [
      "350+ total problems",
      "Can implement Dijkstra & BFS from memory",
      "Comfortable with graph modeling for real-world problems",
    ],
    platforms: ["LeetCode Graph Tag", "CSES Graph Problems", "CP-Algorithms.com"],
  },
  {
    id: 6,
    title: "System Design",
    subtitle: "Sep 15 – Oct 12",
    duration: "Sep 15 – Oct 12 (4 weeks)",
    dateStart: "2026-09-15",
    dateEnd: "2026-10-12",
    icon: "06",
    color: "text-amber-400",
    bgColor: "bg-amber-500",
    gradient: "from-amber-500/20 to-amber-500/0",
    borderColor: "border-amber-500/20",
    goal: "Build strong system design fundamentals for Google's design rounds.",
    topics: [
      { id: "p6-scalability", label: "Scalability: Vertical vs Horizontal Scaling" },
      { id: "p6-latency", label: "Latency, Throughput & Availability (SLAs)" },
      { id: "p6-cap-theorem", label: "CAP Theorem & PACELC" },
      { id: "p6-consistency", label: "Consistency Models: Strong, Eventual, Causal" },
      { id: "p6-tcp-udp", label: "TCP vs UDP, HTTP/HTTPS, HTTP/2, HTTP/3" },
      { id: "p6-rest-grpc", label: "REST vs gRPC vs GraphQL" },
      { id: "p6-websockets", label: "WebSockets & Server-Sent Events" },
      { id: "p6-dns-cdn", label: "DNS Resolution & CDN (CloudFront, Akamai)" },
      { id: "p6-sql", label: "SQL Databases: Indexing, Transactions, ACID" },
      { id: "p6-nosql", label: "NoSQL: Key-Value, Document, Column, Graph DBs" },
      { id: "p6-sharding", label: "Sharding Strategies & Partition Keys" },
      { id: "p6-replication", label: "Replication: Leader-Follower, Multi-Leader, Leaderless" },
      { id: "p6-caching", label: "Caching: Redis, Memcached, LRU/LFU Policies" },
      { id: "p6-cache-strategies", label: "Cache Strategies: Write-Through, Write-Back, Aside" },
      { id: "p6-cache-invalidation", label: "Cache Invalidation & Consistency" },
      { id: "p6-load-balancer", label: "Load Balancing: Round Robin, Consistent Hashing" },
      { id: "p6-message-queues", label: "Message Queues: Kafka, RabbitMQ, Pub/Sub" },
      { id: "p6-rate-limiting", label: "Rate Limiting: Token Bucket, Leaky Bucket, Fixed Window" },
      { id: "p6-api-gateway", label: "API Gateway & Service Discovery" },
      { id: "p6-microservices", label: "Microservices: Circuit Breaker, Saga, CQRS" },
      { id: "p6-blob-storage", label: "Blob / Object Storage (S3, GCS)" },
      { id: "p6-file-systems", label: "Distributed File Systems (GFS, HDFS)" },
      { id: "p6-logging", label: "Logging, Metrics & Distributed Tracing" },
      { id: "p6-design-url", label: "Design: URL Shortener (TinyURL)" },
      { id: "p6-design-twitter", label: "Design: Twitter / News Feed" },
      { id: "p6-design-instagram", label: "Design: Instagram" },
      { id: "p6-design-whatsapp", label: "Design: WhatsApp / Chat System" },
      { id: "p6-design-youtube", label: "Design: YouTube / Video Streaming" },
      { id: "p6-design-uber", label: "Design: Uber / Ride Sharing" },
      { id: "p6-design-netflix", label: "Design: Netflix / Content Delivery" },
      { id: "p6-design-google-drive", label: "Design: Google Drive / Dropbox" },
      { id: "p6-design-google-maps", label: "Design: Google Maps" },
      { id: "p6-design-search", label: "Design: Web Crawler / Search Engine" },
      { id: "p6-design-notification", label: "Design: Notification System" },
      { id: "p6-design-rate-limiter", label: "Design: Distributed Rate Limiter" },
    ],
    practice: "1 full system design per day. Present designs out loud to practice communication.",
    milestones: [
      "20+ system designs completed",
      "Can structure a 45-minute design discussion",
      "Comfortable with trade-off discussions",
    ],
    platforms: ["ByteByteGo", "SystemDesign.one", "Exponent"],
  },
  {
    id: 7,
    title: "Google-Specific & Behavioral",
    subtitle: "Oct 13 – Nov 2",
    duration: "Oct 13 – Nov 2 (3 weeks)",
    dateStart: "2026-10-13",
    dateEnd: "2026-11-02",
    icon: "07",
    color: "text-rose-400",
    bgColor: "bg-rose-500",
    gradient: "from-rose-500/20 to-rose-500/0",
    borderColor: "border-rose-500/20",
    goal: "Prepare specifically for Google's interview process and culture.",
    topics: [
      { id: "p7-google-process", label: "Google Hiring: Phone Screen → Onsite → HC → Team Match" },
      { id: "p7-google-levels", label: "Google Levels: L3 (SDE I), L4 (SDE II), L5 (Senior)" },
      { id: "p7-google-interviewer", label: "What Interviewers Look For: Signals & Rubrics" },
      { id: "p7-googleyness", label: "Googleyness: Collaboration, Intellectual Humility" },
      { id: "p7-ambiguity", label: "Navigating Ambiguity & Asking Clarifying Questions" },
      { id: "p7-pushback", label: "Pushing Back Respectfully & Defending Decisions" },
      { id: "p7-star-method", label: "STAR Method: Situation, Task, Action, Result" },
      { id: "p7-leadership", label: "Leadership Stories (3-5 prepared)" },
      { id: "p7-conflict", label: "Conflict Resolution Stories (3-5 prepared)" },
      { id: "p7-failure", label: "Failure & Learning Stories (3-5 prepared)" },
      { id: "p7-project-deep-dive", label: "Past Project Deep Dives (2-3 projects)" },
      { id: "p7-design-docs", label: "Design: Google Docs (Collaborative Editing)" },
      { id: "p7-design-gmail", label: "Design: Gmail (Email System at Scale)" },
      { id: "p7-design-calendar", label: "Design: Google Calendar" },
      { id: "p7-design-youtube-rec", label: "Design: YouTube Recommendations (ML Pipeline)" },
      { id: "p7-project-1", label: "Project 1: Full-Stack App (demonstrate system design)" },
      { id: "p7-project-2", label: "Project 2: Algorithm-Heavy App (demonstrate DSA)" },
      { id: "p7-project-3", label: "Project 3: Open Source Contribution or API Project" },
      { id: "p7-resume", label: "Resume: Quantified Impact, Google-Friendly Format" },
    ],
    practice: "Mock interviews 3x/week. Record yourself solving problems.",
    milestones: [
      "15+ mock interviews completed",
      "5 prepared STAR stories ready",
      "Confident in structured problem-solving approach",
    ],
    platforms: ["Pramp", "Interviewing.io", "Exponent"],
  },
  {
    id: 8,
    title: "Final Sprint & Mock Interviews",
    subtitle: "Nov 3 – Nov 17",
    duration: "Nov 3 – Nov 17 (2 weeks)",
    dateStart: "2026-11-03",
    dateEnd: "2026-11-17",
    icon: "08",
    color: "text-cyan-400",
    bgColor: "bg-cyan-500",
    gradient: "from-cyan-500/20 to-cyan-500/0",
    borderColor: "border-cyan-500/20",
    goal: "Final review and intense mock interview practice.",
    topics: [
      { id: "p8-blind75", label: "Solve Blind 75 (all reviewed)" },
      { id: "p8-neetcode150", label: "Solve NeetCode 150 (all reviewed)" },
      { id: "p8-google-tagged", label: "LeetCode Google-Tagged Problems (Top 50)" },
      { id: "p8-hard-problems", label: "Hard Problem Sprint (2-3 hards per day)" },
      { id: "p8-timed-practice", label: "Timed Practice: 2 mediums in 45 min" },
      { id: "p8-mock-coding-1", label: "Mock Interview: Coding Round 1" },
      { id: "p8-mock-coding-2", label: "Mock Interview: Coding Round 2" },
      { id: "p8-mock-coding-3", label: "Mock Interview: Coding Round 3" },
      { id: "p8-mock-sd-1", label: "Mock Interview: System Design Round 1" },
      { id: "p8-mock-sd-2", label: "Mock Interview: System Design Round 2" },
      { id: "p8-mock-behavioral", label: "Mock Interview: Behavioral / Googleyness" },
      { id: "p8-mock-full-loop", label: "Full Mock Loop: 4 Rounds Back-to-Back" },
      { id: "p8-review-dp", label: "Review Weak Area: DP Problems" },
      { id: "p8-review-graphs", label: "Review Weak Area: Graph Problems" },
      { id: "p8-review-sd", label: "Review Weak Area: System Design Gaps" },
      { id: "p8-referral", label: "Secure Referral(s) from Google Employees" },
      { id: "p8-application", label: "Submit Google Application" },
      { id: "p8-other-apps", label: "Submit Backup Applications (Meta, Amazon, Microsoft)" },
    ],
    practice: "Full mock interviews every other day. Review ALL mistakes.",
    milestones: [
      "25+ mock interviews completed",
      "400+ LeetCode problems solved",
      "Confident in all interview formats",
    ],
    platforms: ["Pramp", "Interviewing.io", "Exponent", "LeetCode Contest"],
  },
];

/* ─── Companion data ───────────────────────────────────────────── */

export const WEEKLY_PLAN = [
  { day: "Monday", focus: "DSA: Arrays, Strings, Hashing + LeetCode", color: "bg-emerald-500/20 text-emerald-400" },
  { day: "Tuesday", focus: "DSA: Trees, Linked Lists + LeetCode", color: "bg-blue-500/20 text-blue-400" },
  { day: "Wednesday", focus: "DSA: Graphs, BFS/DFS + LeetCode", color: "bg-violet-500/20 text-violet-400" },
  { day: "Thursday", focus: "Dynamic Programming + LeetCode", color: "bg-fuchsia-500/20 text-fuchsia-400" },
  { day: "Friday", focus: "System Design + Design Practice", color: "bg-amber-500/20 text-amber-400" },
  { day: "Saturday", focus: "Project Work + Mock Interview", color: "bg-rose-500/20 text-rose-400" },
  { day: "Sunday", focus: "Review Weak Areas + Behavioral Prep", color: "bg-cyan-500/20 text-cyan-400" },
];

export const TARGETS = [
  { label: "LeetCode Problems", target: "400+", icon: "code" },
  { label: "Portfolio Projects", target: "3", icon: "folder" },
  { label: "Mock Interviews", target: "25+", icon: "mic" },
  { label: "System Designs", target: "20+", icon: "layout" },
];

export const DAILY_COMMITMENT = [
  { activity: "LeetCode problems (med/hard)", hours: 3 },
  { activity: "Data structures & algorithms theory", hours: 2 },
  { activity: "System design study", hours: 1 },
  { activity: "Project work / open source", hours: 1 },
  { activity: "Review & behavioral prep", hours: 1 },
];

export const RESOURCES = [
  { category: "Algorithms", name: "NeetCode Roadmap & Videos", url: "https://neetcode.io/roadmap" },
  { category: "Practice", name: "LeetCode (Google Tag)", url: "https://leetcode.com/company/google" },
  { category: "Practice", name: "Blind 75 Problem List", url: "https://neetcode.io/practice" },
  { category: "System Design", name: "System Design Primer (GitHub)", url: "https://github.com/donnemartin/system-design-primer" },
  { category: "System Design", name: "ByteByteGo (Alex Xu)", url: "https://bytebytego.com" },
  { category: "Behavioral", name: "Exponent Mock Interviews", url: "https://www.tryexponent.com" },
  { category: "CS Fundamentals", name: "MIT OpenCourseWare 6.006", url: "https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020" },
];

/* ─── Default progress & helpers ───────────────────────────────── */

export const DEFAULT_ROADMAP_PROGRESS: RoadmapProgress = {
  phases: ROADMAP_PHASES.map((p) => ({
    phaseId: p.id,
    topicProgress: p.topics.map((t) => ({ topicId: t.id, completed: false })),
    notes: "",
    updatedAt: new Date().toISOString(),
  })),
  problemsSolved: { easy: 0, medium: 0, hard: 0 },
  mockInterviewsDone: 0,
  systemDesignsDone: 0,
  projectsCompleted: [],
  updatedAt: new Date().toISOString(),
};

export function getPhaseProgress(progress: RoadmapProgress, phaseId: number): number {
  const phase = progress.phases.find((p) => p.phaseId === phaseId);
  if (!phase || phase.topicProgress.length === 0) return 0;
  const done = phase.topicProgress.filter((t) => t.completed).length;
  return Math.round((done / phase.topicProgress.length) * 100);
}

export function isTopicCompleted(progress: RoadmapProgress, phaseId: number, topicId: string): boolean {
  const phase = progress.phases.find((p) => p.phaseId === phaseId);
  return phase?.topicProgress.find((t) => t.topicId === topicId)?.completed ?? false;
}

export function toggleTopicProgress(
  progress: RoadmapProgress,
  phaseId: number,
  topicId: string
): RoadmapProgress {
  const phases = progress.phases.map((p) => {
    if (p.phaseId !== phaseId) return p;
    return {
      ...p,
      topicProgress: p.topicProgress.map((t) =>
        t.topicId === topicId
          ? { ...t, completed: !t.completed, completedAt: !t.completed ? new Date().toISOString() : undefined }
          : t
      ),
      updatedAt: new Date().toISOString(),
    };
  });
  return { ...progress, phases, updatedAt: new Date().toISOString() };
}
