import fs from "fs";
import path from "path";
import { ClassifiedService, ExtractedPlan } from "./types";
import { escapeSQL } from "./utils";

export function generateSQLSeed(
  services: ClassifiedService[],
  plans: ExtractedPlan[],
  outputPath: string
): void {
  const lines: string[] = [];
  const now = new Date().toISOString().split("T")[0];

  lines.push(`-- AUTO-GENERATED by scripts/crawl-subscriptions.ts`);
  lines.push(`-- Last generated: ${new Date().toISOString()}`);
  lines.push(`-- Total: ${services.length} services, ${plans.length} plans`);
  lines.push(`-- DO NOT EDIT MANUALLY — re-run the crawler to update`);
  lines.push(``);
  lines.push(`-- Upsert subscription services`);
  lines.push(`INSERT INTO subscription_services (id, name, slug, domain, category, website, logo_url, created_at) VALUES`);

  const serviceValues = services.map((s) => {
    const logoUrl = `https://www.google.com/s2/favicons?domain=${s.domain}&sz=64`;
    return `  ('${escapeSQL(s.id)}', '${escapeSQL(s.name)}', '${escapeSQL(s.slug)}', '${escapeSQL(s.domain)}', '${escapeSQL(s.category)}', '${escapeSQL(s.website)}', '${escapeSQL(logoUrl)}', '${now}')`;
  });

  lines.push(serviceValues.join(",\n"));
  lines.push(`ON CONFLICT (id) DO UPDATE SET`);
  lines.push(`  name = EXCLUDED.name,`);
  lines.push(`  slug = EXCLUDED.slug,`);
  lines.push(`  domain = EXCLUDED.domain,`);
  lines.push(`  category = EXCLUDED.category,`);
  lines.push(`  website = EXCLUDED.website,`);
  lines.push(`  logo_url = EXCLUDED.logo_url;`);
  lines.push(``);

  if (plans.length > 0) {
    lines.push(`-- Upsert subscription plans`);
    lines.push(`INSERT INTO subscription_plans (id, service_id, name, price, currency, billing_cycle, description, created_at) VALUES`);

    const planValues = plans.map((p) => {
      const desc = p.description ? `'${escapeSQL(p.description)}'` : "NULL";
      return `  ('${escapeSQL(p.id)}', '${escapeSQL(p.service_id)}', '${escapeSQL(p.name)}', ${p.price}, 'USD', '${p.billing_cycle}', ${desc}, '${now}')`;
    });

    lines.push(planValues.join(",\n"));
    lines.push(`ON CONFLICT (id) DO UPDATE SET`);
    lines.push(`  name = EXCLUDED.name,`);
    lines.push(`  price = EXCLUDED.price,`);
    lines.push(`  billing_cycle = EXCLUDED.billing_cycle,`);
    lines.push(`  description = EXCLUDED.description;`);
  }

  lines.push(``);

  // Ensure directory exists
  const dir = path.dirname(outputPath);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

  fs.writeFileSync(outputPath, lines.join("\n"));
}
