import fs from "fs";
import path from "path";
import { ClassifiedService, ExtractedPlan } from "./types";

export function generateTypeScriptCatalog(
  services: ClassifiedService[],
  plans: ExtractedPlan[],
  outputPath: string
): void {
  const lines: string[] = [];

  lines.push(`// AUTO-GENERATED by scripts/crawl-subscriptions.ts`);
  lines.push(`// Last generated: ${new Date().toISOString()}`);
  lines.push(`// Total: ${services.length} services, ${plans.length} plans`);
  lines.push(`// DO NOT EDIT MANUALLY — re-run the crawler to update`);
  lines.push(``);
  lines.push(`import { SubscriptionService, SubscriptionPlan } from "@/types";`);
  lines.push(``);
  lines.push(`const favicon = (domain: string) => \`https://www.google.com/s2/favicons?domain=\${domain}&sz=64\`;`);
  lines.push(``);
  lines.push(`export const GENERATED_SUBSCRIPTION_SERVICES: SubscriptionService[] = [`);

  // Sort services by category then name for readability
  const sorted = [...services].sort((a, b) => {
    const catCmp = a.category.localeCompare(b.category);
    return catCmp !== 0 ? catCmp : a.name.localeCompare(b.name);
  });

  let lastCategory = "";
  for (const s of sorted) {
    if (s.category !== lastCategory) {
      lines.push(`  // === ${s.category} ===`);
      lastCategory = s.category;
    }
    const name = JSON.stringify(s.name);
    const slug = JSON.stringify(s.slug);
    const domain = JSON.stringify(s.domain);
    const category = JSON.stringify(s.category);
    const website = JSON.stringify(s.website);
    lines.push(
      `  { id: ${JSON.stringify(s.id)}, name: ${name}, slug: ${slug}, domain: ${domain}, category: ${category}, website: ${website}, logo_url: favicon(${domain}), created_at: "" },`
    );
  }

  lines.push(`];`);
  lines.push(``);

  // Plans grouped by service
  lines.push(`export const GENERATED_SUBSCRIPTION_PLANS: SubscriptionPlan[] = [`);

  // Build service slug -> plans map
  const plansByService = new Map<string, ExtractedPlan[]>();
  for (const p of plans) {
    const arr = plansByService.get(p.service_id) ?? [];
    arr.push(p);
    plansByService.set(p.service_id, arr);
  }

  for (const s of sorted) {
    const sPlans = plansByService.get(s.id);
    if (!sPlans || sPlans.length === 0) continue;

    lines.push(`  // ${s.name}`);
    for (const p of sPlans) {
      const desc = p.description ? JSON.stringify(p.description) : "null";
      lines.push(
        `  { id: ${JSON.stringify(p.id)}, service_id: ${JSON.stringify(p.service_id)}, name: ${JSON.stringify(p.name)}, price: ${p.price}, currency: "USD", billing_cycle: ${JSON.stringify(p.billing_cycle)}, description: ${desc}, created_at: "" },`
      );
    }
  }

  lines.push(`];`);
  lines.push(``);

  // Ensure directory exists
  const dir = path.dirname(outputPath);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

  fs.writeFileSync(outputPath, lines.join("\n"));
}
